import { Button, Card, Empty, Form, Input, InputNumber, Modal, Select, Space, Steps, Table, Tag, Typography, message } from 'antd'
import { useEffect, useRef, useState } from 'react'
import { api } from '../api'; import { RequestComposer } from '../components/RequestComposer'; import { useSession } from '../store'

export function TestingPage(){
  const projectId=useSession(s=>s.projectId);const[scenarios,setScenarios]=useState<any[]>([]);const[interfaces,setInterfaces]=useState<any[]>([]);const[envs,setEnvs]=useState<any[]>([]);const[open,setOpen]=useState(false);const[execution,setExecution]=useState<any>();const socket=useRef<WebSocket>()
  const load=async()=>{if(!projectId)return;const[s,i,e]=await Promise.all([api<any[]>({url:`/projects/${projectId}/scenarios`}),api<any[]>({url:`/projects/${projectId}/interfaces`}),api<any[]>({url:`/projects/${projectId}/environments`})]);setScenarios(s);setInterfaces(i);setEnvs(e)}
  useEffect(()=>{void load();return()=>socket.current?.close()},[projectId])
  if(!projectId)return <Empty description="请先选择项目"/>
  const create=async(v:any)=>{const steps=JSON.parse(v.steps_json);await api({method:'post',url:`/projects/${projectId}/scenarios`,data:{name:v.name,description:v.description||'',scenario_type:'api',priority:v.priority,requirement_module_ids:(v.requirement_module_ids||'').split(',').map((x:string)=>x.trim()).filter(Boolean),steps}});setOpen(false);await load();message.success('场景草稿已创建')}
  const confirm=async(row:any)=>{await api({method:'post',url:`/projects/${projectId}/scenarios/${row.id}/confirm`,params:{revision:row.revision}});await load()}
  const run=async(row:any,envId:string)=>{const data:any=await api({method:'post',url:`/projects/${projectId}/executions`,headers:{'Idempotency-Key':crypto.randomUUID()},data:{scenario_id:row.id,environment_id:envId}});setExecution(data);const token=localStorage.getItem('access_token');const scheme=location.protocol==='https:'?'wss':'ws';socket.current?.close();socket.current=new WebSocket(`${scheme}://${location.host}/ws/projects/${projectId}/executions/${data.id}`);socket.current.onopen=()=>socket.current?.send(JSON.stringify({type:'auth',token}));socket.current.onmessage=(event)=>{const payload=JSON.parse(event.data);if(payload.type==='snapshot')setExecution(payload.data);else void api({url:`/projects/${projectId}/executions/${data.id}`}).then(setExecution)} }
  const defaultSteps=JSON.stringify([{seq:1,name:'登录',interface_id:interfaces[0]?.id||null,request_override:{},preconditions:[],extracts:[{name:'access_token',type:'jmespath',expression:'data.access_token',scope:'scenario',sensitive:true}],assertions:[{type:'status_code',expected:200}],expected_result:'登录成功',timeout_ms:30000,retry_count:0,continue_on_failure:false},{seq:2,name:'鉴权请求',interface_id:interfaces[1]?.id||interfaces[0]?.id||null,request_override:{headers:{Authorization:'Bearer ${access_token}'}},preconditions:[],extracts:[],assertions:[{type:'status_code',expected:200}],expected_result:'鉴权成功',timeout_ms:30000,retry_count:0,continue_on_failure:false}],null,2)
  return <Space direction="vertical" className="page-block" size="large"><Typography.Title level={3}>接口调试与场景</Typography.Title><RequestComposer/><Space className="page-title"><Typography.Title level={4}>场景</Typography.Title><Button type="primary" onClick={()=>setOpen(true)}>创建场景</Button></Space><Table rowKey="id" dataSource={scenarios} columns={[{title:'名称',dataIndex:'name'},{title:'状态',dataIndex:'status',render:v=><Tag>{v}</Tag>},{title:'版本',dataIndex:'version'},{title:'步骤',dataIndex:'steps',render:v=>v.length},{title:'操作',render:(_,r)=><Space><Button disabled={r.status==='confirmed'} onClick={()=>void confirm(r)}>确认</Button><Select placeholder="选择环境执行" style={{width:180}} onChange={id=>void run(r,id)} options={envs.map(e=>({value:e.id,label:e.name}))} disabled={r.status!=='confirmed'}/></Space>}]} />{execution&&<Card title={`执行进度 · ${execution.status}`} extra={<Button disabled={!['pending','running'].includes(execution.status)} onClick={async()=>setExecution(await api({method:'post',url:`/projects/${projectId}/executions/${execution.id}/cancel`}))}>取消</Button>}><Steps direction="vertical" items={(execution.steps||[]).map((s:any)=>({title:s.name,description:s.error_message||`${s.duration_ms||0} ms`,status:s.status==='passed'?'finish':s.status==='running'?'process':s.status==='pending'?'wait':'error'}))}/></Card>}<Modal width={760} open={open} title="创建接口场景" footer={null} onCancel={()=>setOpen(false)}><Form layout="vertical" onFinish={create} initialValues={{priority:'P2',steps_json:defaultSteps}}><Form.Item name="name" label="名称" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="description" label="描述"><Input.TextArea/></Form.Item><Form.Item name="priority" label="优先级"><Select options={['P0','P1','P2','P3'].map(value=>({value}))}/></Form.Item><Form.Item name="requirement_module_ids" label="已确认需求模块 ID（逗号分隔）"><Input/></Form.Item><Form.Item name="steps_json" label="候选步骤 JSON" rules={[{required:true}]}><Input.TextArea rows={18}/></Form.Item><Button type="primary" htmlType="submit">保存草稿</Button></Form></Modal></Space>
}
